syntax on
filetype plugin indent on
set nu
set mouse=a
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent 
set termguicolors
set smartindent
set cursorline
set incsearch
set hlsearch
autocmd FileType c nnoremap <buffer> <F5> :w <bar> !gcc % && ./a.out<CR>
set nu
colorscheme slate
