syntax on
filetype plugin indent on
set nu
set mouse=a
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent 
set termguicolors
set smartindent
set cursorline
set incsearch
set hlsearch
nnoremap <F5> :w<CR>:!gcc %<CR>
set nu
colorscheme slate
